from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict


class BenchmarkRequest(BaseModel):
    """Payload sent to POST /benchmarks/run to trigger an evaluation."""
    target_models: list[str] = Field(
        default=["llama3.2:3b", "phi3:latest", "qwen2.5:3b-instruct"],
        description="List of Ollama model identifiers to benchmark concurrently."
    )
    dataset_path: str = Field(
        default="data/test_cases.json",
        description="Path to ground-truth intent classification dataset."
    )
    monthly_query_scale: int = Field(
        default=1_000_000,
        ge=1,
        description="Target monthly query volume used to project ROI."
    )


class ModelMetricResult(BaseModel):
    """Calculated performance and financial metrics for a single model in a run."""
    model_name: str = Field(..., description="Model identifier (e.g., 'llama3.2:3b')")
    provider_alias: str = Field(..., description="Simulated commercial provider name")
    accuracy: float = Field(..., ge=0.0, le=100.0, description="Exact-match classification accuracy percentage")
    correct_predictions: int = Field(..., ge=0, description="Number of correctly classified prompts")
    total_predictions: int = Field(..., ge=0, description="Total prompts evaluated")
    avg_latency_ms: float = Field(..., ge=0.0, description="Average response latency in milliseconds")
    total_tokens_used: int = Field(..., ge=0, description="Combined prompt + completion tokens used in run")
    projected_monthly_cost_usd: float = Field(..., ge=0.0, description="Simulated monthly cost at specified scale")


class BenchmarkRunResponse(BaseModel):
    """Complete summary response returned by the API and stored in SQLite."""
    run_id: str = Field(..., description="Unique UUID string identifying this run")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="UTC timestamp of run execution")
    total_test_cases: int = Field(..., ge=0, description="Number of benchmark prompts evaluated")
    monthly_query_scale: int = Field(..., description="Query volume scale used for ROI projection")
    summary_report: str = Field(..., description="Executive summary generated by Cloud Synthesis LLM")
    metrics: list[ModelMetricResult] = Field(..., description="Per-model benchmark and ROI results")

    model_config = ConfigDict(from_attributes=True)